Source/UltimateTvGuide.Web/Models/GuideIndexViewModel.cs
using System;
using System.Collections.Generic;

namespace UltimateTvGuide.Web.Models
{
    public class GuideIndexViewModel
    {
        public string Country { get; set; }
        public List<Channel> Channels { get; set; }
        public bool HasChannels => Channels != null && Channels.Count > 0;

        public class Channel
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public Uri LogoUri { get; set; }
            public List<Show> Shows { get; set; }
            public bool HasShows => Shows != null && Shows.Count > 0;
        }

        public class Show
        {
            public string Name { get; set; }
            public DateTimeOffset StartTime { get; set; }
            public DateTimeOffset EndTime { get; set; }
            public int ImdbRating { get; set; }
            public string Plot { get; set; }
            public Uri LogoUri { get; set; }
        }
    }
}

Source/UltimateTvGuide.Web/Models/ModelMapperConfig.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using UltimateTvGuide.Domain.Entities;

namespace UltimateTvGuide.Web.Models
{
    internal static class ModelMapperConfig
    {
        private static IMapper _mapper;

        public static IMapper GetMapper()
        {
            if (_mapper == null)
            {
                IConfigurationProvider config = CreateConfig();
                _mapper = config.CreateMapper();
            }

            return _mapper;
        }

        private static IConfigurationProvider CreateConfig()
        {
            return new MapperConfiguration(c =>
            {
                c.CreateMap<TvGuide, GuideIndexViewModel>()
                    .AfterMap(AfterGuideMap);

                c.CreateMap<TvChannel, GuideIndexViewModel.Channel>()
                .AfterMap(AfterChannelMap);

                c.CreateMap<TvShow, GuideIndexViewModel.Show>();
            });
        }

        private static void AfterChannelMap(TvChannel source, GuideIndexViewModel.Channel destination)
        {
            // Sort shows by start time
            destination.Shows.Sort((f, s) => f.StartTime.CompareTo(s.StartTime));
        }

        private static void AfterGuideMap(TvGuide source, GuideIndexViewModel destination)
        {
            // Remove channels without shows
            destination.Channels.RemoveAll(c => !c.HasShows);

            // Sort channels by name
            destination.Channels.Sort((f, s) => string.Compare(f.Name, s.Name, StringComparison.OrdinalIgnoreCase));
        }
    }
}

Source/UltimateTvGuide.Web/Controllers/GuideController.cs
using System.Web.Mvc;
using AutoMapper;
using UltimateTvGuide.Domain.Entities;
using UltimateTvGuide.Domain.Repositories;
using UltimateTvGuide.Web.Models;

namespace UltimateTvGuide.Web.Controllers
{
    [RoutePrefix("guide")]
    public class GuideController : Controller
    {
        private readonly ITvGuideRepository _tvGuideRepository;
        private readonly IMapper _modelMapper;

        public GuideController()
        {
            _tvGuideRepository = new TvGuideRepository();
            _modelMapper = ModelMapperConfig.GetMapper();
        }

        [HttpGet]
        [Route("{country}", Order = 1)]
        [Route("", Order = 2)]
        public ActionResult Index(string country = null)
        {
            TvGuide tvGuide = _tvGuideRepository.GetByCountry(country);
            GuideIndexViewModel model = _modelMapper.Map<GuideIndexViewModel>(tvGuide);
            return View(model);
        }
    }
}

Source/UltimateTvGuide.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace UltimateTvGuide.Web.Controllers
{
    [RoutePrefix("")]
    public class HomeController : Controller
    {
        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/UltimateTvGuide.Web/Views/Guide/Index.cshtml
@using UltimateTvGuide.Web.Models
@model GuideIndexViewModel
@{
    ViewBag.Title = $"Televisie gids - {Model.Country}";
}
<section class="section-padding">
    @if (Model.HasChannels)
    {
        foreach (var channel in Model.Channels)
        {
            <div class="container">
                <div class="row">
                    <div class="header-section text-center">
                        <h2>@channel.Name</h2>
                        <hr class="bottom-line">
                    </div>
                </div>
                <div class="row">
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Start tijd</th>
                                <th>Eind tijd</th>
                                <th>Naam</th>
                                <th>Beoordeling</th>
                                <th>Omschrijving</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var show in channel.Shows)
                            {
                                <tr>
                                    <td>@show.StartTime.ToString("hh:mm")</td>
                                    <td>@show.EndTime.ToString("hh:mm")</td>
                                    <td>@show.Name</td>
                                    <td>
                                        @if (show.ImdbRating > 0)
                                        {
                                            @($"{show.ImdbRating}/10")
                                        }
                                        else
                                        {
                                            @:Onbekend
                                        }
                                    </td>
                                    <td>@Html.Raw(show.Plot)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        }
    }
    else
    {
        <div class="container">
            <div class="row">
                <div class="header-section text-center">
                    <h2>Geen zenders gevonden.</h2>
                </div>
            </div>
        </div>
    }
</section>

Source/UltimateTvGuide.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welkom";
}

<section id="courses" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="header-section text-center">
                <h2>Gidsen</h2>
                <p>
                    Wij hebben TV gidsen beschikbaar voor allerlei landen. <br />
                    Kies hieronder voor welk land je de programmering wilt zien.
                </p>
                <hr class="bottom-line">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 padleft-right">
                <figure class="imghvr-fold-up">
                    <img src="~/img/tv-flag-nl.jpg" class="img-responsive">
                    <figcaption>
                        <h3>Nederland</h3>
                        <p>Klik hier om de Nederlandse televisie gids te bekijken.</p>
                    </figcaption>
                    <a href="@Url.Action("Index", "Guide", new {country = "nl"})"></a>
                </figure>
            </div>
            <div class="col-md-4 col-sm-6 padleft-right">
                <figure class="imghvr-fold-up">
                    <img src="~/img/tv-flag-gb.jpg" class="img-responsive">
                    <figcaption>
                        <h3>Engeland</h3>
                        <p>Klik hier om de Engelse televisie gids te bekijken.</p>
                    </figcaption>
                    <a href="@Url.Action("Index", "Guide", new {country = "uk"})"></a>
                </figure>
            </div>
            <div class="col-md-4 col-sm-6 padleft-right">
                <figure class="imghvr-fold-up">
                    <img src="~/img/tv-flag-us.jpg" class="img-responsive">
                    <figcaption>
                        <h3>Verenigde Staten</h3>
                        <p>Klik hier om de televisie gids voor de Verenigde Staten te bekijken.</p>
                    </figcaption>
                    <a href="@Url.Action("Index", "Guide", new {country = "us"})"></a>
                </figure>
            </div>
        </div>
    </div>
</section>

Source/UltimateTvGuide.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ultimate TV Guide</title>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/imagehover.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">

    @RenderSection("scripts_top", required: false)
</head>
<body>

    <!--Navigation bar-->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Ultimate <span>TV Guide</span></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Index", "Guide", new {country = "nl"})">Nederland</a></li>
                    <li><a href="@Url.Action("Index", "Guide", new {country = "uk"})">Engeland</a></li>
                    <li><a href="@Url.Action("Index", "Guide", new {country = "us"})">Verenigde Staten</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--/ Navigation bar-->

    <!--Banner-->
    <div class="banner">
        <div class="bg-color">
            <div class="container">
                <div class="row">
                    <div class="banner-text text-center">
                        <div class="text-border">
                            <h2 class="text-dec">@ViewBag.Title</h2>
                        </div>
                        <div class="intro-para text-center quote">
                            <p class="big-text">Alle informatie over je favoriete televisie programma's bij de hand</p>
                            <p class="small-text">De Ultimate TV Guide helpt jou met het vinden van de leukste programma's die je absoluut niet wilt missen.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ Banner-->

    @RenderBody()

    <!--Footer-->
    <footer id="footer" class="footer">
        <div class="container text-center">
            Copyright &copy; <strong>Best IDH15 Group Ever!</strong> 1884-@DateTime.Now.Year
        </div>
    </footer>
    <!--/ Footer-->

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.easing.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    @RenderSection("scripts_bottom", required: false)
</body>
</html>